media:
    input: public/media
    output: /media
components:
    category:
        label: Kategorie
        type: select
        required: true
        options:
            values: [Verein, Junioren, Herren, Frauen, Sonstige]
content:
    - name: teams
      label: Teams
      path: content/teams
      type: collection
      subfolders: false
      view:
          fields: [name, date, category]
          primary: name
          sort: [order, name]
          default:
              search: ''
              sort: order
              order: asc
      fields:
          - name: name
            label: Name
            type: string
            required: true
          - name: description
            label: Description
            type: string
            required: true
          - component: category
            required: true
          - name: league
            label: Spielklasse
            type: string
            required: true
          - name: practice
            label: Trainingszeiten
            list: true
            type: object
            fields:
                - name: day
                  label: Tag(e)
                  type: string
                  required: true
                - name: time
                  label: Uhrzeit
                  type: text
                  required: true
          - name: body
            label: Teaminfo
            type: rich-text
    - name: blog
      label: Blog Post
      path: content/blog
      type: collection
      view:
          fields: [title, date, category, team]
          primary: title
          sort: [date, title]
          default:
              search: ''
              sort: date
              order: desc
      fields:
          - name: title
            label: Titel
            type: string
            required: true
          - name: description
            label: Beschreibung
            type: string
            required: true
          - name: date
            label: Datum
            type: date
            required: true
          - name: team
            label: Team
            type: string
          - component: category
          - name: images
            label: Bilder
            list: true
            type: object
            fields:
                - name: src
                  label: Image
                  type: image
                  required: true
                - name: alt
                  label: Bildbeschreibung
                  type: text
          - name: body
            label: Artikel
            type: rich-text
            required: true
